### ISSUE TITLE
BUG: tox 4 and python3.7 version issue on windows

### ISSUE THREAD

**Issue by bsipocz** [OpenAstronomy/azure-pipelines-templates#86]
See log here:

https://dev.azure.com/astropy-project/pytest-filter-subpackage/_build/results?buildId=6322&view=logs&j=9bbf82d2-fa3a-5bea-3ec4-b956cbc3af4b&t=fa1134d3-5c1e-5fbb-ecc5-74015be7b54e

**Comment by ConorMacBride** [comment]
The log is:
<details><pre>
2022-12-27T16:21:04.0761570Z ##[section]Starting: Running tox
2022-12-27T16:21:04.0924020Z ==============================================================================
2022-12-27T16:21:04.0924806Z Task         : Command line
2022-12-27T16:21:04.0925147Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2022-12-27T16:21:04.0925606Z Version      : 2.212.0
2022-12-27T16:21:04.0925836Z Author       : Microsoft Corporation
2022-12-27T16:21:04.0926297Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2022-12-27T16:21:04.0926778Z ==============================================================================
2022-12-27T16:21:05.3437669Z Generating script.
2022-12-27T16:21:05.3582047Z Script contents: shell
2022-12-27T16:21:05.3596106Z python -m tox -e py37-test  -- --junitxml=junit\test-results.xml --cov-report=xml:D:\a\1\s\coverage.xml
2022-12-27T16:21:05.4094756Z ========================== Starting Command Output ===========================
2022-12-27T16:21:05.4432919Z ##[command]"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\a0f7adce-07f1-47ba-97e3-763a697e62f6.cmd""
2022-12-27T16:21:12.0895429Z .pkg: install_requires> python -I -m pip install setuptools setuptools_scm wheel
2022-12-27T16:21:16.9410287Z .pkg: _optional_hooks> python C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
2022-12-27T16:21:18.9388244Z .pkg: get_requires_for_build_sdist> python C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
2022-12-27T16:21:19.5494698Z .pkg: prepare_metadata_for_build_wheel> python C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
2022-12-27T16:21:20.8156539Z .pkg: build_sdist> python C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
2022-12-27T16:21:21.3033410Z py37-test: install_package_deps> python -I -m pip install pytest pytest-cov pytest-doctestplus pytest>=3.0
2022-12-27T16:21:27.6470558Z py37-test: install_package> python -I -m pip install --force-reinstall --no-deps D:\a\1\s\.tox\.tmp\package\1\pytest-filter-subpackage-0.1.3.dev3+g136c6f0.tar.gz
2022-12-27T16:21:38.6095581Z py37-test: internal error
2022-12-27T16:21:38.6097373Z Traceback (most recent call last):
2022-12-27T16:21:38.6098400Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\loader\ini\__init__.py", line 77, in replacer
2022-12-27T16:21:38.6099446Z     replaced = replace(conf, self, raw_, args_)  # do replacements
2022-12-27T16:21:38.6100449Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\loader\ini\replace.py", line 35, in replace
2022-12-27T16:21:38.6101510Z     replaced = _replace_match(conf, loader, to_replace, args.copy())
2022-12-27T16:21:38.6102453Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\loader\ini\replace.py", line 88, in _replace_match
2022-12-27T16:21:38.6103743Z     replace_value = replace_pos_args(conf, args, conf_args)
2022-12-27T16:21:38.6104785Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\loader\ini\replace.py", line 180, in replace_pos_args
2022-12-27T16:21:38.6105559Z     pos_args = conf.pos_args(to_path)
2022-12-27T16:21:38.6106376Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\main.py", line 55, in pos_args
2022-12-27T16:21:38.6107161Z     if path_arg.exists() and not path_arg.is_absolute():
2022-12-27T16:21:38.6108768Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\pathlib.py", line 1361, in exists
2022-12-27T16:21:38.6109598Z     self.stat()
2022-12-27T16:21:38.6110383Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\pathlib.py", line 1183, in stat
2022-12-27T16:21:38.6111215Z     return self._accessor.stat(self)
2022-12-27T16:21:38.6112163Z OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '--cov-report=xml:D:\\a\\1\\s\\coverage.xml'
2022-12-27T16:21:38.6114161Z 
2022-12-27T16:21:38.6114705Z The above exception was the direct cause of the following exception:
2022-12-27T16:21:38.6115110Z 
2022-12-27T16:21:38.6115540Z Traceback (most recent call last):
2022-12-27T16:21:38.6116407Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\session\cmd\run\single.py", line 46, in _evaluate
2022-12-27T16:21:38.6119000Z     code, outcomes = run_commands(tox_env, no_test)
2022-12-27T16:21:38.6120092Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\session\cmd\run\single.py", line 82, in run_commands
2022-12-27T16:21:38.6121093Z     status_main = run_command_set(tox_env, "commands", chdir, ignore_errors, outcomes)
2022-12-27T16:21:38.6122543Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\session\cmd\run\single.py", line 95, in run_command_set
2022-12-27T16:21:38.6123369Z     command_set: list[Command] = tox_env.conf[key]
2022-12-27T16:21:38.6124318Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\sets.py", line 114, in __getitem__
2022-12-27T16:21:38.6125136Z     return self.load(item)
2022-12-27T16:21:38.6125952Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\sets.py", line 125, in load
2022-12-27T16:21:38.6127364Z     return config_definition.__call__(self._conf, self.loaders, ConfigLoadArgs(chain, self.name, self.env_name))
2022-12-27T16:21:38.6128445Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\of_type.py", line 102, in __call__
2022-12-27T16:21:38.6129268Z     value = loader.load(key, self.of_type, self.factory, conf, args)
2022-12-27T16:21:38.6130123Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\loader\api.py", line 126, in load
2022-12-27T16:21:38.6130927Z     with self.build(future, key, of_type, conf, raw, args) as prepared:
2022-12-27T16:21:38.6131731Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\contextlib.py", line 112, in __enter__
2022-12-27T16:21:38.6132356Z     return next(self.gen)
2022-12-27T16:21:38.6133208Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\loader\ini\__init__.py", line 87, in build
2022-12-27T16:21:38.6133884Z     raw = replacer(raw, args)
2022-12-27T16:21:38.6135274Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\tox\config\loader\ini\__init__.py", line 83, in replacer
2022-12-27T16:21:38.6136042Z     raise HandledError(msg) from exception
2022-12-27T16:21:38.6136904Z tox.report.HandledError: replace failed in py37-test.commands with OSError(22, 'The filename, directory name, or volume label syntax is incorrect')
2022-12-27T16:21:38.6137914Z .pkg: _exit> python C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\pyproject_api\_backend.py True setuptools.build_meta
2022-12-27T16:21:38.6765651Z   py37-test: FAIL code 2 (32.66 seconds)
2022-12-27T16:21:38.6767114Z   evaluation failed :( (32.86 seconds)
2022-12-27T16:21:38.7897372Z ##[error]Cmd.exe exited with code '2'.
2022-12-27T16:21:38.8251681Z ##[section]Finishing: Running tox
</pre></details>
